### ISSUE TITLE
reset password link leads to 500

### ISSUE THREAD

**Issue by dachary** [open-craft/opencraft#112]
When trying to reset password on http://mavoix.opencraft.hosting/ I get

![edx1](https://cloud.githubusercontent.com/assets/433594/16413679/a5979e76-3d33-11e6-9503-74bd0ffffc71.png)

**Comment by antoviaque** [comment]
@dachary Thank you for the report!

Confirmed with the email of the user that had been automatically created based on the registration form (`admin@...`).

@bradenmacdonald For the sprint fireman : )

**Comment by bradenmacdonald** [comment]
@dachary Yep, thanks for reporting this! It looks like a configuration error is preventing the server from sending email. We are working on a fix.

**Comment by dachary** [comment]
thanks :-)

**Comment by bradenmacdonald** [comment]
@dachary The issue should be fixed now. I just tested it, and it seems to work, so it should have sent you a password reset email.

Technical details: the `postfix_queue` ansible role had not been run on the VM. I added it to our branch of Dogwood and now email sending is working as expected.

**Comment by dachary** [comment]
@bradenmacdonald I confirm that a reset mail has been sent. Thanks for a quick resolution !

**Comment by antoviaque** [comment]
Thanks @bradenmacdonald !
