### ISSUE TITLE
only English is available as a language

### ISSUE THREAD

**Issue by dachary** [open-craft/opencraft#114]
When going to http://mavoix.opencraft.hosting/account/settings only English is available. Would it be possible to add more language and french in particular ?

**Comment by antoviaque** [comment]
@dachary That would be possible yes, but it will require some work to make it available - so this would be more a feature request, which we track in the uservoice: https://opencraft.uservoice.com/forums/280754-opencraft/category/134703-opencraft-im - would you mind posting it there?

**Comment by dachary** [comment]
Sure ! https://opencraft.uservoice.com/forums/280754-opencraft/suggestions/15152169-add-languages-to-user-settings

**Comment by antoviaque** [comment]
@dachary Thank you! : )
