### ISSUE TITLE
deleting a course

### ISSUE THREAD

**Issue by dachary** [open-craft/opencraft#116]
It looks like removing a course requires access to the command line : https://openedx.atlassian.net/wiki/display/PLAT/How+to+Delete+a+Course . Is there a way to do that ? Alternatively it would be enough to hide the course so that it does not show in http://mavoix.opencraft.hosting/courses. 

Thanks in advance for your help !

**Comment by antoviaque** [comment]
@dachary Currently deleting a course is only possible from the command-line, so we would need to contribute a feature to the platform to allow to do it from the Web. That's a very frequently requested feature though, that would be very useful to the community as a whole if we got around to do that. Can I also suggest you put it on the UserVoice? : )

In the meantime, yes, there is a way to hide the course - I'm shamelessly copying @bradenmacdonald's good explanation: : )

> If you set both the "Course Start Date" and the "Enrollment Start Date" to a future year like 2030, they will be completely hidden from the site for non-staff users. (Though they will still appear for you since you are a staff user.)

**Comment by dachary** [comment]
Since it's a frequently asked feature, I'll skip it. The workaround is good enough, thanks !

**Comment by dachary** [comment]
The workaround is good for the edx home page http://mavoix.opencraft.hosting/ but the courses still show on http://mavoix.opencraft.hosting/courses . Is there a way to hide them here as well ?

**Comment by dachary** [comment]
I created a new user which is not admin and only the visible course show. That must have been a site effect of me being logged in as admin / staff.
