### ISSUE TITLE
changing the default language for mavoix

### ISSUE THREAD

**Issue by dachary** [open-craft/opencraft#119]
Hi,

I'm not sure how to change the default language to french so that http://mavoix.opencraft.hosting/ shows in French by default. I'll update this issue with my findings.

Cheers

* on a per user basis : https://support.edx.org/hc/en-us/articles/213195078-Can-I-change-the-language-of-the-edX-platform-

**Comment by dachary** [comment]
https://github.com/edx/edx-platform/wiki/Internationalization-and-localization seems to suggest this should be done when running the LSM (it's not a big deal if the studio is in english really)

**Comment by dachary** [comment]
@antoviaque done, thanks !

**Comment by antoviaque** [comment]
For reference - I added the following to `configuration_extra_settings`, and provisioned a new app server with it:

```
EDXAPP_LANG: 'fr_FR.UTF-8'
EDXAPP_ENV_EXTRA:
 LANGUAGE_CODE: 'fr'
```
