### ISSUE TITLE
Link to analytics is broken

### ISSUE THREAD

**Issue by dachary** [open-craft/opencraft#120]
http://mavoix.opencraft.hosting/courses/course-v1:MaVoix+1+2017/instructor#view-instructor_analytics shows a link to http://localhost:18110/courses/courses/course-v1:MaVoix+1+2017

**Comment by antoviaque** [comment]
@dachary Yes, this is a link to insights, which is an optional service and isn't currently provisioned on the service. I don't think there is a way to hide this link when there is no Insight setup though - that might be what we would need to contibute here to avoid the confusion.

**Comment by mtyaka** [comment]
@dachary Thanks for reporting the issue. This has now been fixed - the broken link to analytics is no longer visible.
