### ISSUE TITLE
occasional server error (non fatal)

### ISSUE THREAD

**Issue by dachary** [open-craft/opencraft#122]
From time to time (every 50 click or so) I get an error that displays as shown below. It either auto-resolves and moves on to the next page. Or I just have to retry and it works.

![e2](https://cloud.githubusercontent.com/assets/433594/16837504/fb091ece-49c3-11e6-845b-cc8416038284.png)

**Comment by antoviaque** [comment]
@dachary Do you have way to reproduce it? We have already had similar reports, but there can be different sources for this issue. Is it for example when you switch pages quickly after making a change? It appears when there is an error with the ajax requests saving state in the background, and I've seen that happening. It could also be that some requests take too long.

Any detail would help : )

**Comment by dachary** [comment]
Unfortunately I don't have a way to reproduce that. When/if it happens again, is there anything I could do while the page still shows the error ?

**Comment by antoviaque** [comment]
@dachary Yes, the JS console might have useful info, especially if you have the log/timing of the ajax requests logged there. We will try to set time to have a look at this in any case.

**Comment by antoviaque** [comment]
CC @bradenmacdonald

**Comment by dachary** [comment]
> Yes, the JS console might have useful info, especially if you have the log/timing of the ajax requests logged there.

Ok. Next time I use edX I'll load firebug.

**Comment by bradenmacdonald** [comment]
Thanks @dachary - the "Network" tab will also have helpful information that will help us figure this out, so if you see any errors there as well related to this, please include that.

**Comment by antoviaque** [comment]
@dachary Since there hasn't been any new activity on this, does that mean the error hasn't happened anymore since our original discussion?

I'm closing this bug for now due to inactivity, but just comment/reopen it if this happens to you.

**Comment by dachary** [comment]
This did not happen last time I used edx during one hour continuously and that was last week. Good to close then.

**Comment by antoviaque** [comment]
@dachary Great - thank you for the confirmation! And don't hesitate if that pops up again.
