### ISSUE TITLE
unenroll weird display

### ISSUE THREAD

**Issue by dachary** [open-craft/opencraft#123]
It looks like it should be displayed otherwise, see below.

![e5](https://cloud.githubusercontent.com/assets/433594/16841004/a72b6c3a-49d7-11e6-9fc7-f69d01f68643.png)

**Comment by antoviaque** [comment]
This one would likely be an upstream bug, as we currently use the default theme - can I abuse your good will and ask you to report it upstream? : ) The right project would likely be https://openedx.atlassian.net/secure/RapidBoard.jspa?rapidView=124&projectKey=CRI&view=planning.nodetail

**Comment by dachary** [comment]
Will do :-) What's the easiest way to figure out the edX version that is installed ? http://mavoix.opencraft.hosting/about does not seem to provide it.

**Comment by antoviaque** [comment]
@dachary Thanks! It's running the latest stable version, Dogwood.

**Comment by dachary** [comment]
https://openedx.atlassian.net/secure/RapidBoard.jspa?rapidView=124&projectKey=CRI&view=planning&selectedIssue=CRI-62

**Comment by antoviaque** [comment]
Thank you!

Direct link to the issue: https://openedx.atlassian.net/browse/CRI-62

Closing the current ticket.
