### ISSUE TITLE
CSV report generation problems

### ISSUE THREAD

**Issue by antoviaque** [open-craft/opencraft#126]
From Federico:

> We seem to have some problems generating CSV reports for student profiles and grades.  I attached an image showing the specific problem:  the link for the CSV files are generated in a filesystem directory.  How can we download these files?

![csvgeneration](https://cloud.githubusercontent.com/assets/514483/17476239/429cf27a-5d5f-11e6-8b4d-7eb225e81484.png)

**Comment by haikuginger** [comment]
I've verified that with the upgrade to Eucalyptus, along with related OpenStack fixes, CSV report downloads now work as expected; reports are uploaded into OpenStack on generation, and then are available for download.
