### ISSUE TITLE
Instance can't be accessed

### ISSUE THREAD

**Issue by e-kolpakov** [open-craft/opencraft#2]
Instance manager reports that instance for my [PR](https://github.com/edx/edx-platform/pull/9403) is provisioned and ready, but opening links to LMS and studio still show uservoice forum: 

* LMS: http://pr9403.sandbox.opencraft.com/ 
* Studio: http://studio.pr9403.sandbox.opencraft.com/

**Comment by e-kolpakov** [comment]
@antoviaque ping

**Comment by antoviaque** [comment]
@e-kolpakov I can see the instance there - it suggests DNS cache issues. Can you try to resolve the IP in your shell, and see if that points to the same one as your browser?

It should show:

```
$ host pr9403.sandbox.opencraft.com
pr9403.sandbox.opencraft.com has address 149.202.176.40
```

**Comment by e-kolpakov** [comment]
$ host pr9403.sandbox.opencraft.com
    pr9403.sandbox.opencraft.com has address 149.202.176.40

**Comment by antoviaque** [comment]
So your DNS seem to be fine, but if you're still seeing it in your browser, he might be still using the old IP. Try to load it in a new tab and/or clear your cache?

**Comment by e-kolpakov** [comment]
@antoviaque new tab does not help. Incognito mode or other browser does however. Didn't know Chrome is caching DNS :)

**Comment by antoviaque** [comment]
Ok, good to know in any case, that issue might popup again.
