### ISSUE TITLE
Doesn't manage Time zones and Date format

### ISSUE THREAD

**Issue by SlyMaVoix** [open-craft/opencraft#200]
It is impossible into opencraft to manage time zones and Date format.
All dates and times are configurable only with one format an one time zone:

mm/dd/yyyy and HH::MM (UTC)

Is it possible to manage others time zones and date format, based from the country or language parameter somewhere ?

**Comment by antoviaque** [comment]
I think in Studio this is currently set in UTC, regardless of the Timezone setting - right @bdero ?

CC @bradenmacdonald

**Comment by bdero** [comment]
@SlyMaVoix @antoviaque Yup, this is still true I believe. It's possible to change the timezone used for display in the LMS, but there isn't a way to configure the Studio interface to use anything other than UTC times.

**Comment by antoviaque** [comment]
@bdero Thank you for checking!

@SlyMaVoix This is thus an upstream limitation of the Open edX project - this would have to be contributed by someone to https://open.edx.org/

**Comment by SlyMaVoix** [comment]
Thank you for your answer ! @antoviaque and @bdero
