### ISSUE TITLE
[BB-1032] copyright should be updated

### ISSUE THREAD

**Issue by ghost** [open-craft/opencraft#227]
https://console.opencraft.com/ should have s/2016/2017/

Nit :-)

**Comment by bradenmacdonald** [comment]
Thanks for noticing - this should be automatically updated to the current year. It may take us a while to get to this fix.

**Comment by maltouzes** [comment]
Affect line 10 in footer.html:
https://github.com/open-craft/opencraft/blob/d891795e7bf7a568222331859403e9584dbf22c3/templates/footer.html#L10

**Comment by dupainaulevain** [comment]
It has been updated (twice ;-) ) since but ... 2019 is still to be done. I suspect this will happen every year. Unless something really spectacular happens and we switch to having longer years?

**Comment by antoviaque** [comment]
@dupainaulevain That is something that can be done as part of another task, maybe? To add to the scope of an upcoming task, including coming back to close this ticket?
