### ISSUE TITLE
[SE-709] migrate from tlslite to tlslite-ng

### ISSUE THREAD

**Issue by tomato42** [open-craft/opencraft#339]
[`tlslite`](https://github.com/trevp/tlslite) is effectively abandoned (no new commits for 3 years); migrate to [`tlslite-ng`](https://github.com/tomato42/tlslite-ng) as it is maintained and developed (yearly releases)

I'm the primary developer of tlslite-ng and former main contributor to tlslite.

**Comment by bradenmacdonald** [comment]
Thanks for letting us know, @tomato42. We are planning to make that change, but don't have a timeline yet.

**Comment by clemente** [comment]
We fixed this in a recent global upgrade and clean-up. `tlslite` was required by some other package we used, but we didn't need this package anymore so we removed it. There's no `tlslite` in requirements.txt now.

@tomato42 Thanks for notifying users of the old package!

**Comment by tomato42** [comment]
honestly, I'm glad the resolution was removal – as the security policy points out, it's not exactly the safest TLS implementation around... :)
