### ISSUE TITLE
how to manually create an instance?

### ISSUE THREAD

**Issue by singuliere** [open-craft/opencraft#393]
After starting the server with `make run.dev` I see an empty page. I'm told an instance should be created manually so the interface shows. How can I do that?

![b](https://user-images.githubusercontent.com/35190819/53889486-cf28c000-4026-11e9-820c-eddc95a36831.png)

**Comment by singuliere** [comment]
I think https://github.com/open-craft/opencraft#manual-provisioning is what I'm looking for

**Comment by singuliere** [comment]
The missing bit was that these commands need to be run in a python interpret obtained with `make manage shell`. :tada: 
![c](https://user-images.githubusercontent.com/35190819/53892338-65abb000-402c-11e9-872f-3e78ab1b9fed.png)

**Comment by antoviaque** [comment]
@dupainaulevain Thanks for already having resolved this :) It would be worth adding the bit that was missing to you to https://github.com/open-craft/opencraft#manual-provisioning for future reference?

**Comment by singuliere** [comment]
@antoviaque yes, this issue will be closed once #394 is merged

**Comment by singuliere** [comment]
@antoviaque oh, I see you closed the issue already. Is it intentional?

**Comment by UmanShahzad** [comment]
@singuliere Since that PR is trivial we can assume it can be merged immediately after tests pass (well, I also left a small comment), so I guess no need to keep around the issue.

**Comment by antoviaque** [comment]
@UmanShahzad Yup exactly - although if this didn't end up solving the issue for you @singuliere don't hesitate to reopen it.
