### ISSUE TITLE
[BB-1030] code coverage is not collected from integration tests

### ISSUE THREAD

**Issue by singuliere** [open-craft/opencraft#397]
The [integration tests](https://github.com/open-craft/opencraft/blob/master/Makefile#L115) run with

    honcho run ./manage.py test ...

And do not collect coverage. They should run with **--append**:

    honcho coverage run --append --source='.' --omit='*/tests/*,venv/*' run ./manage.py test ...

Or using another file to store coverage so they can both be combined to figure out coverage.

**Comment by antoviaque** [comment]
@UmanShahzad Another review to schedule :)

Can I let you or @dupainaulevain create a Jira task in the Ocim tech debt for any ticket contributed that remain open here? If we move the project to an open jira that won't be necessary anymore.

**Comment by UmanShahzad** [comment]
Thanks, looks like BB-1030 was created by @dupainaulevain .

**Comment by antoviaque** [comment]
@UmanShahzad @dupainaulevain  Perfect - thanks!
