### ISSUE TITLE
Installation doc needs to mention provisioning the virtualbox

### ISSUE THREAD

**Issue by lsiden** [open-craft/opencraft#729]
When I ran "make migration" inside my new OCIM virtual box as per the [installation instructions](https://ocim.opencraft.com/en/latest/installation/), it failed. It complained "coverage: command not found". I installed pip3, then coverage, ran "make migrate" again and this time it was missing "honcho".

In order to get it to just work, I had to quite the virtualbox and run "vagrant provision", then "vagrant reload".  Then, in the virtualbox, "make migration" finished successfully.

The command "vagrant help up" shows that --provision is a default for "vagrant up" so this extra step should not have been required, but that's what I needed to do to get that to work.

I propose to update the Installation doc page to note this.  I will create a PR soon.

**Comment by lgp171188** [comment]
This was found to be an invalid issue. Closing.
