### ISSUE TITLE
Change user's directory into the opencraft directory after ssh into the virtual box 

### ISSUE THREAD

**Issue by tinumide** [open-craft/opencraft#836]
In the installation process of OCIM [here](https://ocim.opencraft.com/en/latest/installation/), after a user does an ssh into the virtual box, the user should be in the opencraft directory before proceeding with other commands such as `make migrate`.

**Comment by karimelghazouly** [comment]
![Screenshot from 2022-01-26 11-08-17](https://user-images.githubusercontent.com/24472871/151134573-63dd3c3c-0cd1-4158-9522-4480af4fb445.png)
@tinumide this seems to be fixed by now
